### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by MarshallJD1** [MarshallJD1/MiniHackathon#1]
Expense tracker needs 3 inputs to allow user to specify what expense , when and where 
the submitted information is stored in a table below with a hover over delete button.: 

To Do

- [ ] Expense name user input box
- [ ] Date user input box
- [ ] Amount user input box
- [ ] Submit button 
- [ ] Table below showing submitted information
- [ ] Submitted item has hover over delete button
